version: '3.8'

services:
  react-builder:
    image: node:18-alpine
    volumes:
      - ./app:/app
      - apache-html:/apache-html
      - node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/Ryvexam/ryvexam-website.git . &&
        npm install &&
        npm run build &&
        cp -r build/* /apache-html/"

  apache:
    image: httpd:2.4-alpine
    ports:
      - "4567:80"
    volumes:
      - apache-html:/usr/local/apache2/htdocs/
    depends_on:
      - react-builder

volumes:
  apache-html:
  node_modules: