version: '3.8'

services:
  react-app:
    image: node:18-alpine
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/Ryvexam/ryvexam-website.git . &&
        npm install &&
        npm run build &&
        npm install -g serve &&
        serve -s build -l 3000"

volumes:
  node_modules: